from __future__ import annotations

from datetime import UTC, datetime
import hashlib
import importlib.util
import json
from pathlib import Path
import re
import sys
from typing import Any

from wiki_tool.catalog import DEFAULT_DB
from wiki_tool.markdown import normalize_name
from wiki_tool.study_streams import (
    DEFAULT_BOOK_MANIFEST,
    DEFAULT_DEFINITION_CARDS,
    DEFAULT_INDEX,
    DEFAULT_READER_STREAM,
    DEFAULT_STUDY_DIR,
    DEFAULT_STUDY_SELECTION,
    DEFAULT_STUDY_SHELF,
    DEFAULT_STUDY_SOURCE_ROOT,
    MATERIALIZED_STATUSES,
    clean_source_text,
    is_display_quality_card_term,
    is_junk_section,
    is_structural_card_term,
    normalize_chapter_title,
    resolve_index_book,
    study_inventory,
    validate_shelf,
)


DEFAULT_STUDY_QA_DIR = Path("state/study_quality")
DEFAULT_STUDY_QA_EVIDENCE_LIMIT = 3
DEFAULT_STUDY_QA_TERM_LIMIT = 5
DEFAULT_FINAL_REVIEW_PACKET = "final_review_packet.md"
DEFAULT_ARCHIVE_DIRNAME = "archive"
LEGACY_DEFICIENCY_REPORTS = (
    "corpus_deficiency_list.md",
    "deficiency_inventory.json",
)
REPRESENTATIVE_REVIEW_BOOKS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("billingsley_probability_measure", ("ch_01",)),
    ("capinski_kopp_measure_integral_probability", ("ch_05",)),
    ("murphy_advanced_topics", ("ch_07", "ch_17", "ch_27")),
    ("tao_higher_order_fourier_analysis", ("ch_01",)),
    ("boyd_convex_optimization", ("ch_01",)),
)
SEVERE = "severe"
WARN = "warn"
PASS = "pass"
FAIL = "fail"

INCOMPLETE_EXTRACT = "incomplete_extract"
MISSING_BUILD_ARTIFACT = "missing_build_artifact"
EMPTY_READER = "empty_reader"
READER_JUNK = "reader_junk"
BAD_TITLE = "bad_title"
ZERO_CARD_DECK = "zero_card_deck"
THIN_CARD_DECK = "thin_card_deck"
STRUCTURAL_CARD_TERM = "structural_card_term"
WEAK_CARD_TERM = "weak_card_term"
UPSTREAM_NOISY_CARD_LABEL = "upstream_noisy_card_label"
BOOK_OVERVIEW_BAD_CHAPTER_LABEL = "book_overview_bad_chapter_label"
READER_PAGE_JUNK_RESIDUE = "reader_page_junk_residue"
DEFINITIONS_INDEX_NOISY_HEADING = "definitions_index_noisy_heading"
RESULTS_INDEX_NOISY_HEADING = "results_index_noisy_heading"

SEVERE_CATEGORIES = {
    INCOMPLETE_EXTRACT,
    MISSING_BUILD_ARTIFACT,
    EMPTY_READER,
    READER_JUNK,
    ZERO_CARD_DECK,
}
WARN_CATEGORIES = {
    BAD_TITLE,
    THIN_CARD_DECK,
    STRUCTURAL_CARD_TERM,
    WEAK_CARD_TERM,
    UPSTREAM_NOISY_CARD_LABEL,
    BOOK_OVERVIEW_BAD_CHAPTER_LABEL,
    READER_PAGE_JUNK_RESIDUE,
    DEFINITIONS_INDEX_NOISY_HEADING,
    RESULTS_INDEX_NOISY_HEADING,
}
READER_BLOCKING_CATEGORIES = {
    INCOMPLETE_EXTRACT,
    MISSING_BUILD_ARTIFACT,
    EMPTY_READER,
    READER_JUNK,
}
FLASHCARD_BLOCKING_CATEGORIES = {
    INCOMPLETE_EXTRACT,
    MISSING_BUILD_ARTIFACT,
    ZERO_CARD_DECK,
}
JUNK_RE = re.compile(
    r"(subject index|name index|table of contents|z-library|singlelogin|downloaded from|generated by unregistered)",
    re.IGNORECASE,
)
INDEX_LIKE_RE = re.compile(
    r"(author index|notation|index of notation|selected published titles in this series|pure and applied mathematics)",
    re.IGNORECASE,
)
ROW_TITLE_JUNK_RE = re.compile(
    r"(author index|subject index|name index|notation index|index of notation|selected published titles in this series|pure and applied mathematics)",
    re.IGNORECASE,
)
ROW_TEXT_JUNK_RE = re.compile(
    r"(a wiley-interscience series of texts|founded by richard courant|numbers in square brackets following each entry give the pages of this book|selected published titles in this series|author index|subject index|name index)",
    re.IGNORECASE,
)
CONTENTS_HINT_RE = re.compile(r"\b(preface|chapter|appendix|contents?)\b", re.IGNORECASE)
PAGE_NUMBER_CLUSTER_RE = re.compile(r"\b\d{1,4}(?:\.\d+)*(?:[-–]\d{1,4})?\b")
BAD_TITLE_RE = re.compile(r"(_|\b\dEd\b|\bVol \d\b)", re.IGNORECASE)
STRUCTURAL_CARD_RE = re.compile(
    r"\b(preface|appendix|proof|example|remark|exercise|problem|problems|section|chapter)\b",
    re.IGNORECASE,
)


def study_quality_summary(
    db_path: Path = DEFAULT_DB,
    *,
    generated_at_utc: str | None = None,
    output_dir: Path = DEFAULT_STUDY_DIR,
    qa_output_dir: Path = DEFAULT_STUDY_QA_DIR,
    shelf: str = DEFAULT_STUDY_SHELF,
) -> dict[str, Any]:
    normalized_shelf = validate_shelf(shelf)
    shelf_root = output_dir / normalized_shelf
    books = load_audited_books(db_path=db_path, shelf_root=shelf_root, shelf=normalized_shelf)
    issue_counts = build_issue_counts(books)
    qa_root = qa_output_dir / normalized_shelf
    consumer_checks = build_consumer_checks(shelf_root)
    generated_at = generated_at_utc or utc_now()
    core = {
        "book_count": len(books),
        "books": [book_summary(book) for book in books],
        "built_count": sum(1 for book in books if book["status"] == "built"),
        "catalog_db": str(db_path),
        "completion_bar": "quality_done",
        "consumer_checks": consumer_checks,
        "flashcard_ready_count": sum(1 for book in books if book["flashcard_ready"]),
        "generated_at_utc": generated_at,
        "issue_counts": issue_counts,
        "output_dir": str(shelf_root),
        "qa_output_dir": str(qa_root.resolve()),
        "reader_ready_count": sum(1 for book in books if book["reader_ready"]),
        "shelf": normalized_shelf,
    }
    summary_sha256 = compute_summary_sha256(core)
    report_statuses = collect_report_statuses(qa_root, summary_sha256)
    completion = build_completion_status(issue_counts, consumer_checks)
    priority_queue = build_priority_queue(books)
    return {
        **core,
        "canonical_status_path": str((qa_root / "summary.json").resolve()),
        "completion_status": completion["completion_status"],
        "priority_queue": priority_queue,
        "remaining_severe_count": completion["remaining_severe_count"],
        "remaining_warning_count": completion["remaining_warning_count"],
        "report_statuses": report_statuses,
        "summary_sha256": summary_sha256,
    }


def study_quality_show(
    db_path: Path = DEFAULT_DB,
    identifier: str = "",
    *,
    output_dir: Path = DEFAULT_STUDY_DIR,
    shelf: str = DEFAULT_STUDY_SHELF,
) -> dict[str, Any]:
    normalized_shelf = validate_shelf(shelf)
    shelf_root = output_dir / normalized_shelf
    books = load_merged_books(db_path=db_path, shelf_root=shelf_root, shelf=normalized_shelf)
    entry = resolve_index_book(books, identifier)
    detail = audit_book_entry(shelf_root, entry)
    detail["catalog_db"] = str(db_path)
    detail["generated_at_utc"] = utc_now()
    detail["output_dir"] = str(shelf_root)
    detail["shelf"] = normalized_shelf
    return detail


def write_study_quality_reports(
    db_path: Path = DEFAULT_DB,
    *,
    output_dir: Path = DEFAULT_STUDY_DIR,
    qa_output_dir: Path = DEFAULT_STUDY_QA_DIR,
    shelf: str = DEFAULT_STUDY_SHELF,
) -> dict[str, Any]:
    target_root = qa_output_dir / validate_shelf(shelf)
    target_root.mkdir(parents=True, exist_ok=True)
    books_root = target_root / "books"
    books_root.mkdir(parents=True, exist_ok=True)
    archived_files = archive_legacy_reports(target_root)
    generated_at = utc_now()

    summary = study_quality_summary(
        db_path,
        generated_at_utc=generated_at,
        output_dir=output_dir,
        qa_output_dir=qa_output_dir,
        shelf=shelf,
    )

    summary_path = target_root / "summary.json"
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    readme_path = target_root / "README.md"
    readme_path.write_text(render_study_quality_summary_markdown(summary), encoding="utf-8")
    final_review_path = target_root / DEFAULT_FINAL_REVIEW_PACKET
    final_review_path.write_text(
        render_final_review_packet(summary, output_dir=output_dir, shelf=validate_shelf(shelf)),
        encoding="utf-8",
    )

    summary = study_quality_summary(
        db_path,
        generated_at_utc=generated_at,
        output_dir=output_dir,
        qa_output_dir=qa_output_dir,
        shelf=shelf,
    )
    summary_path.write_text(json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    readme_path.write_text(render_study_quality_summary_markdown(summary), encoding="utf-8")
    final_review_path.write_text(
        render_final_review_packet(summary, output_dir=output_dir, shelf=validate_shelf(shelf)),
        encoding="utf-8",
    )

    files = [str(summary_path), str(readme_path), str(final_review_path)]
    flagged_books = 0
    shelf_root = output_dir / validate_shelf(shelf)
    current_flagged_paths: set[Path] = set()
    for entry in load_merged_books(db_path=db_path, shelf_root=shelf_root, shelf=validate_shelf(shelf)):
        detail = audit_book_entry(shelf_root, entry)
        if not detail["issues"]:
            continue
        flagged_books += 1
        path = books_root / f"{detail['document_id']}.md"
        current_flagged_paths.add(path)
        path.write_text(render_study_quality_book_markdown(detail), encoding="utf-8")
        files.append(str(path))
    for path in books_root.glob("*.md"):
        if path not in current_flagged_paths:
            path.unlink()

    return {
        "archived_files": archived_files,
        "book_count": summary["book_count"],
        "catalog_db": str(db_path),
        "completion_bar": summary["completion_bar"],
        "completion_status": summary["completion_status"],
        "file_count": len(files),
        "files": files,
        "flagged_book_count": flagged_books,
        "generated_at_utc": summary["generated_at_utc"],
        "output_dir": str(target_root),
        "priority_queue_count": len(summary["priority_queue"]),
        "remaining_severe_count": summary["remaining_severe_count"],
        "remaining_warning_count": summary["remaining_warning_count"],
        "shelf": summary["shelf"],
        "summary_sha256": summary["summary_sha256"],
    }


def load_study_index(shelf_root: Path) -> dict[str, Any]:
    index_path = shelf_root / DEFAULT_INDEX
    if not index_path.exists():
        raise ValueError(f"study materials not built in {shelf_root}; run `wiki study build` first")
    return json.loads(index_path.read_text(encoding="utf-8"))


def load_audited_books(*, db_path: Path, shelf_root: Path, shelf: str) -> list[dict[str, Any]]:
    return [audit_book_entry(shelf_root, entry) for entry in load_merged_books(db_path=db_path, shelf_root=shelf_root, shelf=shelf)]


def load_merged_books(*, db_path: Path, shelf_root: Path, shelf: str) -> list[dict[str, Any]]:
    index = load_study_index(shelf_root)
    inventory_books = infer_inventory_books(db_path=db_path, shelf_root=shelf_root, shelf=shelf, index=index)
    manifest_books = discover_manifest_books(shelf_root)
    return merge_quality_books(index.get("books") or [], inventory_books, manifest_books)


def infer_inventory_books(*, db_path: Path, shelf_root: Path, shelf: str, index: dict[str, Any]) -> list[dict[str, Any]]:
    source_root_value = str(index.get("source_root") or "").strip()
    source_root = Path(source_root_value) if source_root_value else DEFAULT_STUDY_SOURCE_ROOT
    selection = str(index.get("selection") or DEFAULT_STUDY_SELECTION)
    try:
        inventory = study_inventory(
            db_path,
            source_root=source_root,
            shelf=shelf,
            selection=selection,
        )
    except Exception:
        return []
    return [dict(book) for book in inventory["books"]]


def discover_manifest_books(shelf_root: Path) -> dict[str, dict[str, Any]]:
    books: dict[str, dict[str, Any]] = {}
    if not shelf_root.exists():
        return books
    for manifest_path in sorted(shelf_root.glob(f"*/{DEFAULT_BOOK_MANIFEST}"), key=lambda path: path.parent.name):
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        document_id = str(manifest["document_id"])
        books[document_id] = {
            "book_title": str(manifest.get("book_title") or document_id),
            "definition_card_count": int(manifest.get("definition_card_count") or 0),
            "document_id": document_id,
            "has_source_note": bool(manifest.get("has_source_note")),
            "manifest_path": str(manifest_path),
            "note_path": manifest.get("note_path"),
            "row_count": int(manifest.get("row_count") or 0),
            "status": str(manifest.get("status") or "built"),
            "title_source": str(manifest.get("title_source") or "book_manifest"),
        }
    return books


def merge_quality_books(
    index_books: list[dict[str, Any]],
    inventory_books: list[dict[str, Any]],
    manifest_books: dict[str, dict[str, Any]],
) -> list[dict[str, Any]]:
    merged: dict[str, dict[str, Any]] = {}
    for entry in index_books:
        document_id = str(entry["document_id"])
        merged[document_id] = dict(entry)
    for entry in inventory_books:
        document_id = str(entry["document_id"])
        existing = merged.get(document_id, {})
        merged[document_id] = {
            **existing,
            **entry,
            "book_title": str(entry.get("book_title") or existing.get("book_title") or document_id),
            "document_id": document_id,
            "has_source_note": bool(entry.get("has_source_note") or existing.get("has_source_note")),
            "note_path": entry.get("note_path") or existing.get("note_path"),
            "title_source": str(entry.get("title_source") or existing.get("title_source") or ""),
        }
    for document_id, entry in manifest_books.items():
        existing = merged.get(document_id, {})
        merged[document_id] = {
            **existing,
            **entry,
            "book_title": str(entry.get("book_title") or existing.get("book_title") or document_id),
            "document_id": document_id,
            "has_source_note": bool(entry.get("has_source_note") or existing.get("has_source_note")),
            "note_path": entry.get("note_path") or existing.get("note_path"),
            "title_source": str(entry.get("title_source") or existing.get("title_source") or ""),
        }
    books = list(merged.values())
    books.sort(key=lambda item: (str(item.get("document_id") or ""), str(item.get("book_title") or "")))
    return books


def audit_book_entry(shelf_root: Path, entry: dict[str, Any]) -> dict[str, Any]:
    detail = {
        "book_title": str(entry.get("book_title") or ""),
        "blocked_reasons": {"flashcard": [], "reader": []},
        "definition_card_count": int(entry.get("definition_card_count") or 0),
        "document_id": str(entry["document_id"]),
        "flashcard_ready": False,
        "has_source_note": bool(entry.get("has_source_note")),
        "issues": [],
        "manifest_path": str(entry.get("manifest_path") or ""),
        "note_path": entry.get("note_path"),
        "qa_status": PASS,
        "reader_ready": False,
        "row_count": int(entry.get("row_count") or 0),
        "status": str(entry.get("status") or ""),
        "title_source": str(entry.get("title_source") or ""),
    }
    status = detail["status"]
    if status in {"partial", "no_valid_chapters"}:
        detail["issues"].append(
            issue(
                INCOMPLETE_EXTRACT,
                SEVERE,
                {"status": status, "skipped_chapter_count": len(entry.get("skipped_chapters") or [])},
            )
        )

    if status not in MATERIALIZED_STATUSES:
        finalize_book_issues(detail)
        return detail

    book_root = shelf_root / detail["document_id"]
    reader_stream_path = book_root / DEFAULT_READER_STREAM
    cards_path = book_root / DEFAULT_DEFINITION_CARDS
    manifest_path = book_root / DEFAULT_BOOK_MANIFEST
    missing = [
        str(path.name)
        for path in (reader_stream_path, cards_path, manifest_path)
        if not path.exists()
    ]
    if missing:
        detail["issues"].append(issue(MISSING_BUILD_ARTIFACT, SEVERE, {"missing_files": missing}))
        finalize_book_issues(detail)
        return detail

    if is_bad_title(detail["book_title"]):
        detail["issues"].append(
            issue(
                BAD_TITLE,
                WARN,
                {"book_title": detail["book_title"], "title_source": detail["title_source"]},
            )
        )

    rows = load_jsonl(reader_stream_path)
    cards = load_jsonl(cards_path)
    detail["row_count"] = len(rows)
    detail["definition_card_count"] = len(cards)

    if not rows:
        detail["issues"].append(issue(EMPTY_READER, SEVERE, {"row_count": 0}))
    else:
        junk_rows = [
            {
                "reader_text": str(row.get("reader_text") or "")[:280],
                "row_id": str(row.get("row_id") or ""),
                "title_path": str(row.get("title_path") or ""),
            }
            for row in rows
            if JUNK_RE.search(f"{row.get('title_path', '')}\n{row.get('reader_text', '')}")
        ][:DEFAULT_STUDY_QA_EVIDENCE_LIMIT]
        if junk_rows:
            detail["issues"].append(issue(READER_JUNK, SEVERE, {"rows": junk_rows}))

    if not cards:
        detail["issues"].append(issue(ZERO_CARD_DECK, SEVERE, {"definition_card_count": 0}))
    elif len(cards) < 10:
        detail["issues"].append(
            issue(THIN_CARD_DECK, WARN, {"definition_card_count": len(cards)})
        )

    structural_terms = []
    seen_terms: set[str] = set()
    for card in cards:
        term = str(card.get("term") or "").strip()
        normalized = normalize_name(term)
        if not term or normalized in seen_terms:
            continue
        if is_structural_card_term(term):
            seen_terms.add(normalized)
            structural_terms.append(term)
        if len(structural_terms) >= DEFAULT_STUDY_QA_TERM_LIMIT:
            break
    if structural_terms:
        detail["issues"].append(issue(STRUCTURAL_CARD_TERM, WARN, {"terms": structural_terms}))

    weak_terms = []
    upstream_noisy_terms = []
    definition_heading_noise = []
    result_heading_noise = []
    seen_weak_terms: set[str] = set()
    for card in cards:
        term = str(card.get("term") or "").strip()
        source_kind = str(card.get("card_source_kind") or "")
        normalized = normalize_name(term)
        if not term or normalized in seen_weak_terms:
            continue
        if not is_display_quality_card_term(term, source_kind=source_kind):
            seen_weak_terms.add(normalized)
            weak_terms.append(term)
            upstream_noisy_terms.append(
                {
                    "source_kind": source_kind,
                    "term": term,
                }
            )
            if source_kind in {"definition_heading", "inline_definition", "strict_concept"}:
                definition_heading_noise.append(term)
            if source_kind in {"named_theorem", "named_lemma", "named_proposition", "named_corollary"}:
                result_heading_noise.append(term)
        if len(weak_terms) >= DEFAULT_STUDY_QA_TERM_LIMIT:
            break
    if weak_terms:
        detail["issues"].append(issue(WEAK_CARD_TERM, WARN, {"terms": weak_terms}))
        detail["issues"].append(issue(UPSTREAM_NOISY_CARD_LABEL, WARN, {"terms": upstream_noisy_terms}))
    if definition_heading_noise:
        detail["issues"].append(issue(DEFINITIONS_INDEX_NOISY_HEADING, WARN, {"terms": definition_heading_noise[:DEFAULT_STUDY_QA_TERM_LIMIT]}))
    if result_heading_noise:
        detail["issues"].append(issue(RESULTS_INDEX_NOISY_HEADING, WARN, {"terms": result_heading_noise[:DEFAULT_STUDY_QA_TERM_LIMIT]}))

    bad_chapter_labels = []
    seen_bad_labels: set[str] = set()
    for chapter in entry.get("chapters") or []:
        chapter_title = str(chapter.get("title") or chapter.get("chapter_title") or "").strip()
        chapter_number = chapter.get("chapter_number")
        if chapter_label_needs_attention(chapter_title, chapter_number=chapter_number):
            normalized = normalize_name(chapter_title)
            if normalized and normalized in seen_bad_labels:
                continue
            if normalized:
                seen_bad_labels.add(normalized)
            bad_chapter_labels.append(
                {
                    "chapter_id": str(chapter.get("chapter_id") or ""),
                    "chapter_number": chapter_number,
                    "chapter_title": chapter_title,
                }
            )
        if len(bad_chapter_labels) >= DEFAULT_STUDY_QA_EVIDENCE_LIMIT:
            break
    if bad_chapter_labels:
        detail["issues"].append(issue(BOOK_OVERVIEW_BAD_CHAPTER_LABEL, WARN, {"chapters": bad_chapter_labels}))

    reader_page_junk_rows = []
    for row in rows:
        title_path = str(row.get("title_path") or "")
        reader_text = str(row.get("reader_text") or "")
        if row_looks_like_page_junk(title_path, reader_text):
            reader_page_junk_rows.append(
                {
                    "reader_text": reader_text[:280],
                    "row_id": str(row.get("row_id") or ""),
                    "title_path": title_path,
                }
            )
        if len(reader_page_junk_rows) >= DEFAULT_STUDY_QA_EVIDENCE_LIMIT:
            break
    if reader_page_junk_rows:
        detail["issues"].append(issue(READER_PAGE_JUNK_RESIDUE, WARN, {"rows": reader_page_junk_rows}))

    finalize_book_issues(detail)
    return detail


def finalize_book_issues(detail: dict[str, Any]) -> None:
    severe_issue_count = sum(1 for item in detail["issues"] if item["severity"] == SEVERE)
    warning_issue_count = sum(1 for item in detail["issues"] if item["severity"] == WARN)
    categories = [item["category"] for item in detail["issues"]]
    detail["issue_count"] = len(detail["issues"])
    detail["issue_categories"] = categories
    detail["severe_issue_count"] = severe_issue_count
    detail["warning_issue_count"] = warning_issue_count
    detail["blocked_reasons"] = {
        "reader": [category for category in categories if category in READER_BLOCKING_CATEGORIES],
        "flashcard": [category for category in categories if category in FLASHCARD_BLOCKING_CATEGORIES],
    }
    detail["reader_ready"] = (
        detail["status"] in MATERIALIZED_STATUSES
        and detail["row_count"] > 0
        and not detail["blocked_reasons"]["reader"]
    )
    detail["flashcard_ready"] = (
        detail["status"] in MATERIALIZED_STATUSES
        and detail["definition_card_count"] > 0
        and not detail["blocked_reasons"]["flashcard"]
    )
    if severe_issue_count:
        detail["qa_status"] = FAIL
    elif warning_issue_count:
        detail["qa_status"] = WARN
    else:
        detail["qa_status"] = PASS


def build_issue_counts(books: list[dict[str, Any]]) -> dict[str, Any]:
    by_category = {category: 0 for category in sorted(SEVERE_CATEGORIES | WARN_CATEGORIES)}
    by_severity = {SEVERE: 0, WARN: 0}
    flagged_books = 0
    for book in books:
        if book["issues"]:
            flagged_books += 1
        for item in book["issues"]:
            by_category[item["category"]] += 1
            by_severity[item["severity"]] += 1
    return {
        "by_category": by_category,
        "by_severity": by_severity,
        "flagged_book_count": flagged_books,
    }


def build_completion_status(issue_counts: dict[str, Any], consumer_checks: dict[str, Any]) -> dict[str, Any]:
    severe = int(issue_counts["by_severity"][SEVERE])
    warn = int(issue_counts["by_severity"][WARN])
    consumer_failed = any(
        check.get("required_for_completion") and check.get("status") == FAIL
        for check in consumer_checks.values()
    )
    return {
        "completion_status": PASS if severe == 0 and warn == 0 and not consumer_failed else FAIL,
        "remaining_severe_count": severe,
        "remaining_warning_count": warn,
    }


def compute_summary_sha256(summary_core: dict[str, Any]) -> str:
    payload = json.dumps(summary_core, indent=2, sort_keys=True).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def build_consumer_checks(shelf_root: Path) -> dict[str, Any]:
    check = run_vox_study_library_smoke(shelf_root)
    return {"vox_study_library": check}


def run_vox_study_library_smoke(shelf_root: Path) -> dict[str, Any]:
    repo_root = Path(__file__).resolve().parents[1]
    vox_root = repo_root.parent / "vox"
    study_library_path = vox_root / "app" / "study_library.py"
    if not study_library_path.exists():
        return {
            "required_for_completion": False,
            "status": "skip",
            "reason": f"missing vox study_library at {study_library_path}",
        }
    try:
        spec = importlib.util.spec_from_file_location("vox_study_library_smoke", study_library_path)
        if spec is None or spec.loader is None:
            raise ImportError(f"cannot load spec for {study_library_path}")
        module = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = module
        spec.loader.exec_module(module)
        books = module.load_study_books(root=shelf_root)
        by_id = {book.document_id: book for book in books}
        available_representative = [
            (document_id, chapter_ids)
            for document_id, chapter_ids in REPRESENTATIVE_REVIEW_BOOKS
            if document_id in by_id
        ]
        required = len(available_representative) == len(REPRESENTATIVE_REVIEW_BOOKS)
        if not available_representative:
            return {
                "checked_books": [],
                "repo_root": str(vox_root),
                "required_for_completion": False,
                "reason": "representative review set unavailable in current study shelf",
                "status": "skip",
            }
        checked: list[dict[str, Any]] = []
        for document_id, chapter_ids in available_representative:
            book = by_id[document_id]
            rows = module.load_reader_rows(book)
            if not rows:
                raise ValueError(f"empty reader rows for {document_id}")
            rendered_book = module.render_book_text(book, rows)
            if not rendered_book.strip():
                raise ValueError(f"empty rendered book text for {document_id}")
            checked_entry = {
                "document_id": document_id,
                "row_count": len(rows),
            }
            if chapter_ids:
                chapter_text = module.render_chapter_text(book, rows, chapter_ids[0])
                if not chapter_text.strip():
                    raise ValueError(f"empty rendered chapter text for {document_id}:{chapter_ids[0]}")
                checked_entry["chapter_id"] = chapter_ids[0]
            checked.append(checked_entry)
        return {
            "checked_books": checked,
            "repo_root": str(vox_root),
            "required_for_completion": required,
            "reason": None if required else "representative review set unavailable in current study shelf",
            "status": PASS,
        }
    except Exception as exc:
        return {
            "error": str(exc),
            "repo_root": str(vox_root),
            "required_for_completion": True,
            "status": FAIL,
        }


def collect_report_statuses(target_root: Path, summary_sha256: str) -> dict[str, dict[str, Any]]:
    statuses: dict[str, dict[str, Any]] = {}
    for filename in ("README.md", DEFAULT_FINAL_REVIEW_PACKET):
        path = target_root / filename
        if not path.exists():
            statuses[filename] = {"path": str(path), "status": "missing"}
            continue
        text = path.read_text(encoding="utf-8")
        embedded = extract_report_source_hash(text)
        statuses[filename] = {
            "path": str(path),
            "source_summary_sha256": embedded,
            "status": "current" if embedded == summary_sha256 else "stale",
        }
    for filename in LEGACY_DEFICIENCY_REPORTS:
        path = target_root / filename
        statuses[filename] = {
            "path": str(path),
            "status": "stale_conflicting" if path.exists() else "absent",
        }
    return statuses


def extract_report_source_hash(text: str) -> str | None:
    match = re.search(r"^- source_summary_sha256: `([0-9a-f]{64})`$", text, re.MULTILINE)
    if match is None:
        return None
    return match.group(1)


def archive_legacy_reports(target_root: Path) -> list[str]:
    archived: list[str] = []
    stale_paths = [target_root / filename for filename in LEGACY_DEFICIENCY_REPORTS if (target_root / filename).exists()]
    if not stale_paths:
        return archived
    stamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    archive_root = target_root / DEFAULT_ARCHIVE_DIRNAME / stamp
    archive_root.mkdir(parents=True, exist_ok=True)
    for path in stale_paths:
        target = archive_root / path.name
        path.rename(target)
        archived.append(str(target))
    return archived


def build_priority_queue(books: list[dict[str, Any]]) -> list[dict[str, Any]]:
    flagged = [book for book in books if book["issues"]]
    flagged.sort(key=priority_sort_key)
    return [book_summary(book) for book in flagged]


def priority_sort_key(book: dict[str, Any]) -> tuple[int, int, int, int, str]:
    categories = set(book["issue_categories"])
    if READER_JUNK in categories or EMPTY_READER in categories:
        group = 0
    elif book["severe_issue_count"] > 0:
        group = 1
    else:
        group = 2
    return (
        group,
        -book["severe_issue_count"],
        -book["warning_issue_count"],
        -book["issue_count"],
        str(book["document_id"]),
    )


def book_summary(book: dict[str, Any]) -> dict[str, Any]:
    return {
        "blocked_reasons": book["blocked_reasons"],
        "book_title": book["book_title"],
        "definition_card_count": book["definition_card_count"],
        "document_id": book["document_id"],
        "flashcard_ready": book["flashcard_ready"],
        "has_source_note": book["has_source_note"],
        "issue_categories": book["issue_categories"],
        "issue_count": book["issue_count"],
        "qa_status": book["qa_status"],
        "reader_ready": book["reader_ready"],
        "row_count": book["row_count"],
        "severe_issue_count": book["severe_issue_count"],
        "status": book["status"],
        "title_source": book["title_source"],
        "warning_issue_count": book["warning_issue_count"],
    }


def issue(category: str, severity: str, evidence: dict[str, Any]) -> dict[str, Any]:
    return {
        "category": category,
        "evidence": evidence,
        "severity": severity,
    }


def is_bad_title(title: str) -> bool:
    cleaned = title.strip()
    if not cleaned:
        return True
    if BAD_TITLE_RE.search(cleaned):
        return True
    return cleaned == cleaned.lower()


def chapter_label_needs_attention(chapter_title: str, *, chapter_number: int | None) -> bool:
    cleaned = chapter_title.strip()
    if not cleaned:
        return True
    normalized = normalize_chapter_title(cleaned, chapter_number=chapter_number)
    if cleaned != normalized:
        return True
    if re.search(r"\s\d{1,4}$", cleaned):
        return True
    if "|" in cleaned:
        return True
    return False


def row_looks_like_page_junk(title_path: str, reader_text: str) -> bool:
    compact = clean_source_text(f"{title_path}\n{reader_text}")
    clean_title = clean_source_text(title_path)
    clean_reader = clean_source_text(reader_text)
    if JUNK_RE.search(compact):
        return True
    if ROW_TITLE_JUNK_RE.search(clean_title):
        return True
    if ROW_TEXT_JUNK_RE.search(clean_reader):
        return True
    if is_junk_section(title_path, reader_text):
        return True
    lines = [line.strip() for line in reader_text.splitlines() if line.strip()]
    if len(lines) >= 3 and sum(1 for line in lines[:20] if re.match(r"^[A-Z][A-Z ,.'’\\*&]+[—-]", line.strip("`* "))) >= 3:
        return True
    if looks_like_contents_dump(clean_reader, lines):
        return True
    return False


def looks_like_contents_dump(clean_reader: str, lines: list[str]) -> bool:
    if not lines:
        return False
    has_code_fence = clean_reader.startswith("```")
    stripped = clean_reader.strip()
    table_like_lines = [
        line
        for line in lines[:10]
        if line.startswith("|")
        or line.endswith("|")
        or re.fullmatch(r"[|:\- ]{5,}", line) is not None
    ]
    if not has_code_fence:
        if len(lines) >= 3:
            if len(table_like_lines) < 3:
                return False
        elif not (
            stripped.startswith("|")
            and stripped.endswith("|")
            and stripped.count("|") >= 8
        ):
            return False
    sample = " ".join(line.strip("`*| ") for line in lines[:10])
    hint_hits = len(CONTENTS_HINT_RE.findall(sample))
    number_hits = len(PAGE_NUMBER_CLUSTER_RE.findall(sample))
    section_hits = len(re.findall(r"\b\d+\.\d+\b", sample))
    if len(lines) == 1 and "chapter" in sample.lower() and section_hits >= 2 and number_hits >= 4:
        return True
    if hint_hits >= 2 and number_hits >= 4:
        return True
    if "preface" in sample.lower() and number_hits >= 3:
        return True
    if "table of contents" in sample.lower():
        return True
    if "chapter" in sample.lower() and section_hits >= 2 and number_hits >= 4:
        return True
    return False


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def render_study_quality_summary_markdown(summary: dict[str, Any]) -> str:
    lines = [
        "# Study Quality Report",
        "",
        f"- generated_at_utc: `{summary['generated_at_utc']}`",
        f"- source_summary_generated_at_utc: `{summary['generated_at_utc']}`",
        f"- source_summary_sha256: `{summary['summary_sha256']}`",
        f"- source_completion_status: `{summary['completion_status']}`",
        f"- catalog_db: `{summary['catalog_db']}`",
        f"- output_dir: `{summary['output_dir']}`",
        f"- qa_output_dir: `{summary['qa_output_dir']}`",
        f"- canonical_status_path: `{summary['canonical_status_path']}`",
        f"- shelf: `{summary['shelf']}`",
        f"- completion_bar: `{summary['completion_bar']}`",
        f"- completion_status: `{summary['completion_status']}`",
        f"- book_count: `{summary['book_count']}`",
        f"- built_count: `{summary['built_count']}`",
        f"- flagged_book_count: `{summary['issue_counts']['flagged_book_count']}`",
        f"- remaining_severe_count: `{summary['remaining_severe_count']}`",
        f"- remaining_warning_count: `{summary['remaining_warning_count']}`",
        f"- reader_ready_count: `{sum(1 for book in summary['books'] if book['reader_ready'])}`",
        f"- flashcard_ready_count: `{sum(1 for book in summary['books'] if book['flashcard_ready'])}`",
        "",
        "## Issue Counts",
        "",
    ]
    for severity, count in summary["issue_counts"]["by_severity"].items():
        lines.append(f"- {severity}: `{count}`")
    lines.extend(["", "### Categories", ""])
    for category, count in summary["issue_counts"]["by_category"].items():
        lines.append(f"- {category}: `{count}`")
    lines.extend(["", "## Priority Queue", ""])
    if not summary["priority_queue"]:
        lines.append("- none")
    else:
        for item in summary["priority_queue"]:
            cats = ", ".join(item["issue_categories"]) or "none"
            lines.append(
                f"- `{item['document_id']}`: `{item['qa_status']}` with `{item['issue_count']}` issues ({cats}); reader_ready=`{'true' if item['reader_ready'] else 'false'}`, flashcard_ready=`{'true' if item['flashcard_ready'] else 'false'}`"
            )
    lines.extend(["", "## Consumer Checks", ""])
    for name, check in summary["consumer_checks"].items():
        lines.append(f"- {name}: `{check['status']}`")
        if check.get("repo_root"):
            lines.append(f"  - repo_root: `{check['repo_root']}`")
        if check.get("error"):
            lines.append(f"  - error: `{check['error']}`")
        if check.get("reason"):
            lines.append(f"  - reason: `{check['reason']}`")
        if check.get("checked_books"):
            checked = ", ".join(item["document_id"] for item in check["checked_books"])
            lines.append(f"  - checked_books: `{checked}`")
    lines.extend(["", "## Report Status", ""])
    for name, status in summary["report_statuses"].items():
        lines.append(f"- {name}: `{status['status']}`")
    return "\n".join(lines).strip() + "\n"


def render_study_quality_book_markdown(detail: dict[str, Any]) -> str:
    lines = [
        f"# Study QA: {detail['book_title']}",
        "",
        f"- document_id: `{detail['document_id']}`",
        f"- qa_status: `{detail['qa_status']}`",
        f"- source_note: `{'true' if detail['has_source_note'] else 'false'}`",
        f"- title_source: `{detail['title_source']}`",
        f"- build_status: `{detail['status']}`",
        f"- row_count: `{detail['row_count']}`",
        f"- definition_card_count: `{detail['definition_card_count']}`",
        f"- reader_ready: `{'true' if detail['reader_ready'] else 'false'}`",
        f"- flashcard_ready: `{'true' if detail['flashcard_ready'] else 'false'}`",
    ]
    if detail.get("note_path"):
        lines.append(f"- note_path: `{detail['note_path']}`")
    if detail.get("manifest_path"):
        lines.append(f"- manifest_path: `{detail['manifest_path']}`")
    if detail["blocked_reasons"]["reader"]:
        lines.append(f"- reader_blocked_by: `{', '.join(detail['blocked_reasons']['reader'])}`")
    if detail["blocked_reasons"]["flashcard"]:
        lines.append(f"- flashcard_blocked_by: `{', '.join(detail['blocked_reasons']['flashcard'])}`")
    lines.extend(["", "## Issues", ""])
    if not detail["issues"]:
        lines.append("- none")
        return "\n".join(lines).strip() + "\n"
    for item in detail["issues"]:
        lines.append(f"### {item['category']}")
        lines.append("")
        lines.append(f"- severity: `{item['severity']}`")
        evidence = item["evidence"]
        for key, value in evidence.items():
            if isinstance(value, list):
                lines.append(f"- {key}:")
                for record in value:
                    if isinstance(record, dict):
                        compact = ", ".join(f"{subkey}={record[subkey]!r}" for subkey in sorted(record))
                        lines.append(f"  - {compact}")
                    else:
                        lines.append(f"  - {value}")
            else:
                lines.append(f"- {key}: `{value}`")
        lines.append("")
    return "\n".join(lines).strip() + "\n"


def utc_now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


def render_final_review_packet(
    summary: dict[str, Any],
    *,
    output_dir: Path,
    shelf: str,
) -> str:
    shelf_root = output_dir / shelf
    repo_root = Path(__file__).resolve().parents[1]
    math_library_root = repo_root / "state" / "wiki_mirror" / "projects" / "math_library"
    books_by_id = {book["document_id"]: book for book in summary["books"]}
    lines = [
        "# Final Review Packet",
        "",
        f"- generated_at_utc: `{utc_now()}`",
        f"- source_summary_generated_at_utc: `{summary['generated_at_utc']}`",
        f"- source_summary_sha256: `{summary['summary_sha256']}`",
        f"- source_completion_status: `{summary['completion_status']}`",
        f"- shelf: `{summary['shelf']}`",
        f"- completion_bar: `{summary['completion_bar']}`",
        f"- completion_status: `{summary['completion_status']}`",
        f"- remaining_severe_count: `{summary['remaining_severe_count']}`",
        f"- remaining_warning_count: `{summary['remaining_warning_count']}`",
        "",
        "## Canonical Gate",
        "",
        "- QA summary: [summary.json](summary.json)",
        "- Written QA overview: [README.md](README.md)",
        "- Generated Math Library hub: [Math Library Hub](../../wiki_mirror/projects/math_library/README.md)",
        "",
        "## Consumer Check",
        "",
    ]
    vox_check = summary["consumer_checks"]["vox_study_library"]
    lines.append(f"- vox_study_library: `{vox_check['status']}`")
    if vox_check.get("repo_root"):
        lines.append(f"- vox_repo_root: `{vox_check['repo_root']}`")
    if vox_check.get("checked_books"):
        lines.append(
            "- checked_books: `"
            + ", ".join(item["document_id"] for item in vox_check["checked_books"])
            + "`"
        )
    if vox_check.get("error"):
        lines.append(f"- error: `{vox_check['error']}`")
    if vox_check.get("reason"):
        lines.append(f"- reason: `{vox_check['reason']}`")
    lines.extend(["", "## Representative Books", ""])
    for document_id, chapter_ids in REPRESENTATIVE_REVIEW_BOOKS:
        book = books_by_id.get(document_id)
        if book is None:
            continue
        lines.append(f"### {book['book_title']}")
        lines.append("")
        lines.append(f"- document_id: `{document_id}`")
        lines.append(
            f"- book page: [overview](../../wiki_mirror/projects/math_library/books/{document_id}/README.md)"
        )
        chapter_links = []
        for chapter_id in chapter_ids:
            chapter_path = math_library_root / "books" / document_id / "chapters" / f"{chapter_id}.md"
            if chapter_path.exists():
                chapter_links.append(
                    f"[{chapter_id}](../../wiki_mirror/projects/math_library/books/{document_id}/chapters/{chapter_id}.md)"
                )
        if chapter_links:
            lines.append(f"- sample chapter{'s' if len(chapter_links) > 1 else ''}: " + ", ".join(chapter_links))
        lines.append("- study artifacts:")
        lines.append(f"  - [manifest](../../study_materials/{shelf}/{document_id}/manifest.json)")
        lines.append(f"  - [reader stream](../../study_materials/{shelf}/{document_id}/reader_stream.jsonl)")
        lines.append(f"  - [definition cards](../../study_materials/{shelf}/{document_id}/definition_cards.jsonl)")
        disco_path = shelf_root / document_id / "discoflash_definition_matching.txt"
        if disco_path.exists():
            lines.append(
                f"  - [discoflash](../../study_materials/{shelf}/{document_id}/discoflash_definition_matching.txt)"
            )
        lines.append("- review:")
        lines.append(f"  - `qa_status={book['qa_status']}`")
        lines.append(f"  - `reader_ready={'true' if book['reader_ready'] else 'false'}`")
        lines.append(f"  - `flashcard_ready={'true' if book['flashcard_ready'] else 'false'}`")
        lines.append(f"  - `definition_card_count={book['definition_card_count']}`")
        lines.append(f"  - `row_count={book['row_count']}`")
        lines.append("")
    lines.extend(
        [
            "## Closeout Notes",
            "",
            f"- `study qa summary --json` is the canonical machine-readable status authority at `{summary['canonical_status_path']}`.",
            "- `final_review_packet.md` and `README.md` are derived snapshots tied to the source summary hash above.",
            "- Legacy contradictory deficiency reports are archived under `state/study_quality/math/archive/` when `study qa write` runs.",
            "- Generated pages, cross-book indexes, flashcard exports, and `vox` study-library loading all consume the same built study corpus.",
        ]
    )
    return "\n".join(lines).strip() + "\n"
